name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Create Archive
      uses: thedoctor0/zip-release@master
      with:
        filename: 'whitelist.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Push Archive
      uses: EndBug/add-and-commit@v7
      with:
        message: 'Whitelist updated.'
        add: 'whitelist.zip'
